= Building pipleine for your containers

This lab demonstrates Github Actions, which provides the ability to do continuous integration/continuous delivery (CI/CD) from within your Github projects.he lab will lead you through the anatomy of how Github Actions solve this problem. You can apply the same pipeline structure to other CI tools like Concourse or Jenkins.

== Learning Outcomes
After completing the lab, you will be able to:


 . Describe how to create pipeline to deploy an application to VMWare Enterprise PKS
 . Describe anatomy of Github Actions to build the pipeline
 . Continuously deploy your code to PKS  
 

Before starting the lab, pull in the pipeline-start task.
   
   git cherry-pick pipeline-start
  
We can then navigate to GitHub and view the solution tags. This is handy when you get stuck during a lab and need a little help.
== Open the project in Intellij IDE

.   Create a settings.gradle file in the root project directory with below content

+
[source,java]
---------------------------------------------------------------------
rootProject.name = 'pages'
---------------------------------------------------------------------
== Add an endpoint to your application

. We need to create PageApplication.java and HelloController.java based on test classes
. Create a package org.dell.kube.pages under src/main/java
. Create class PageApplication.java in the package with below content

 
+
[source, java, numbered]
---------------------------------------------------------------------
ppackage org.dell.kube.pages;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class PageApplication {

	public static void main(String[] args) {
		SpringApplication.run(PageApplication.class, args);
	}
}
---------------------------------------------------------------------

. Create HomeController.java with below content in same package

+
[source, java, numbered]
---------------------------------------------------------------------
package org.dell.kube.pages;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/")
public class HomeController {


    @GetMapping
    public String getPage(){
        return "Hello from page : YellowPages";
    }


}
---------------------------------------------------------------------

. Add actuator dependency to the list of dependencies in build.gradle inside the dependencies closure
+ 
[source,java]
---------------------------------------------------------------------
implementation 'org.springframework.boot:spring-boot-starter-actuator'
---------------------------------------------------------------------

. Add the following in both test and src application.properties
. Add the below content in both the properties files
+  

[source,java]
---------------------------------------------------------------------
spring.application.name=pages
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
---------------------------------------------------------------------

. Build & test the application
+ 

[source,java]
---------------------------------------------------------------------
./gradlew clean build
---------------------------------------------------------------------

. Run the application
+ 

[source,java]
---------------------------------------------------------------------
./gradlew bootRun
---------------------------------------------------------------------

. Browse to 
+

[source,java]
---------------------------------------------------------------------
Browse to http://localhost:8080
---------------------------------------------------------------------