= Building pipleine for your containers

This lab demonstrates Github Actions, which provides the ability to do continuous integration/continuous delivery (CI/CD) from within your Github projects.he lab will lead you through the anatomy of how Github Actions solve this problem. You can apply the same pipeline structure to other CI tools like Concourse or Jenkins.

== Learning Outcomes
After completing the lab, you will be able to:


 . Describe how to create pipeline to deploy an application to VMWare Enterprise PKS
 . Describe anatomy of Github Actions to build the pipeline
 . Continuously deploy your code to PKS  
 

Before starting the lab, pull in the pipeline-start task.
   
   git cherry-pick pipeline-start
  

As part of this cherry pick you will pipeline.yaml file under the folder ./github/workflows

This is your pipeline file which gets executed on your every git commit.
Replace the tag-name and docker-user-name appropriately in the pipeline .



Create the following secrets in your github repository. To create secrets access the settings section of your repository and select secrets.



[source,java]
---------------------------------------------------------------------
DOCKER_USERNAME
DOCKER_PASSWORD
PKS_USERNAME
PKS_PASSWORD
PKS_API
PKS_CLUSTER
---------------------------------------------------------------------

Push your code to git repository and wait till git actions starts the build and deploys to the  PKS cluster



Access your application 


[source,java]
---------------------------------------------------------------------
Browse to 
---------------------------------------------------------------------