= Building a Spring Boot Application

== Learning Outcomes
After completing the lab, you will be able to:

 . Describe how to create runnable Spring Boot application
 . Describe how to create a controller that responds to HTTP requests
 . Use gradle to run gradle tasks
 
The pages codebase contains a local Git repository with the starting points and the solutions for all the labs in this unit. Download the linked zip file and extract the codebase in the ~/workspace directory. The extracted directory will contains a single text file as well as the (hidden) Git files. You will be building up the code in this directory bit by bit, and we have provided reference implementations at each stage identified by tags in the Git repository. Take some time to navigate through the tags and branches using the following command: 
   
   git log --graph --decorate --oneline --all
   
Create a repository called pages in your GitHub account. Add this repository as a remote called origin of your local repository. You will push all of your work to this repository during the next few labs.

We will start by pushing the initial commit to GitHub, complete with the start and solutions tags.

  git push origin master --tags
  
We can then navigate to GitHub and view the solution tags. This is handy when you get stuck during a lab and need a little help.

== Add an endpoint to your application

. Create a class HomeController.java under the package org.dell.kube.pages with the following content.
+
[source, java, numbered]
---------------------------------------------------------------------
package org.dell.kube.pages;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/")
public class HomeController {


    @GetMapping
    public String getPage(){
        return "Hello from page : YellowPages";
    }


}
---------------------------------------------------------------------

. Add the following request handler to the class _io.pivotal.CloudNativeSpringApplication (/cloud-native-spring/src/main/java/io/pivotal/CloudNativeSpringApplication.java).
+
[source,java]
---------------------------------------------------------------------
@RequestMapping("/")
public String hello() {
    return "Hello World!";
}
---------------------------------------------------------------------
+
Completed:
+
[source,java]
---------------------------------------------------------------------
package io.pivotal;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class CloudNativeSpringApplication {

    public static void main(String[] args) {
        SpringApplication.run(CloudNativeSpringApplication.class, args);
    }

    @RequestMapping("/")
    public String hello() {
        return "Hello World!";
    }
}
---------------------------------------------------------------------

