= Externalize Configuration in Kubernetes

== Learning Outcomes
After completing the lab, you will be able to:

 . Use environment variables to configure an application running locally
 . Describe how to configure a Spring Boot application on Kubernetes with ConfigMap

 
Before starting the lab, pull in the config-start task.
   
   git cherry-pick config-start
   
== Externalize the welcome message

.   Verify the HomeControllerTest.java file to check the change in test. The HomeController.java needs 
    to be changed to pass the test case
.   In HomeController.java create a String variable pageContent and intialize it through constructor
    using @Value annotation. Use the same variable in getPage() method to return welcome message.

+
[source,java]
---------------------------------------------------------------------
package org.dell.kube.pages;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/")
public class HomeController {

    private String pageContent;

    public HomeController(@Value("${page.content}") String pageContent){
        this.pageContent=pageContent;

    }
    @GetMapping
    public String getPage(){
        return "Hello from page : "+pageContent+" ";
    }


}
---------------------------------------------------------------------

.   Initialize the variable PAGE_CONTENT in build.gradle for bootRun and test closures by adding below 
    statements


+
[source, java, numbered]
---------------------------------------------------------------------
bootRun.environment([
		"PAGE_CONTENT": "YellowPages",
])

test.environment([
		"PAGE_CONTENT": "YellowPages",
])
---------------------------------------------------------------------

This would supply the value for pageContent during test and bootRun gradle tasks.

. Build and Test the application 

+
[source, java, numbered]
---------------------------------------------------------------------
./gradlew clean build
./gradlew bootRun
---------------------------------------------------------------------

. Build your container
+ 
[source,java]
---------------------------------------------------------------------
docker build -t <docker_username>/<docker_repo>:config .
---------------------------------------------------------------------

. Run your container
+  

[source,java]
---------------------------------------------------------------------
docker run -p 8080:8080 -t <docker_username>/<docker_repo>:config
---------------------------------------------------------------------


. Browse to 
+

[source,java]
---------------------------------------------------------------------
Browse to http://localhost:8080
---------------------------------------------------------------------