== Putting your container to the Kubernetes cluster

== Learning Outcomes
After completing the lab, you will be able to:

 . Describe how to create Kubernetes Objects
 . Describe how to write yaml files for pods, deployments and services
 . Run your Spring boot application as a docker container
 
== Get started 
Before starting the lab, pull in the kubernetes-start task.
   
   git cherry-pick kubernetes-start
   
As part of this checkout you will get three yaml files - pages-namespace.yaml, pages-services.yaml, pages-deployment.yaml

. Fill in the pages-namespace.yaml as below 

+
[source,java]
---------------------------------------------------------------------
Assign your <first-name> to the name section
---------------------------------------------------------------------

.   Fill in the pages-services.yaml as below


+
[source,java]
---------------------------------------------------------------------
Assign 8080 to targetPort and port
Assign TCP to protocol
Assign the value pages to app, servicefor and name
In metadata section add namespace: <your-name>
---------------------------------------------------------------------

.   Fill in the pages-deployment.yaml
+
[source,java]
---------------------------------------------------------------------
Assign the value pages to app, servicefor and name
Assign proper values for <docker_username>/pages:kube for value of image.
In metadata section add namespace: <your-name>
---------------------------------------------------------------------

In all the above section replace <your-name> with your own first name. 

Instructions for the application to be deployed in minikube for local testing

minikube and kubectl must be installed in the local machine vm. To start minikube "minikube start" or "minikube start --driver=virtualbox/docker" could be executed in the terminal.


. Change type in pages-service.yaml to NodePort

. Run the following commands in terminal to run the application in minikube


+
[source,java]
---------------------------------------------------------------------
kubectl -f deployment/pages-namespace.yaml
kubectl -f deployment/pages-service.yaml
kubectl -f deployment/pages-deployment.yaml
---------------------------------------------------------------------  

. The above commands will create a namespace in the name <your-name> and a deployment, service called pages under the same namespace. Verify the namespace, deployment and service are created by using the following command

+
[source,java]
---------------------------------------------------------------------
kubectl get deployment pages --namespace <your-name>
kubectl get service pages --namespace <your-name>
---------------------------------------------------------------------  

. Below command would set your default namespace to the new namespace and we don't need to suffix --namespace in all commands

[source,java]
---------------------------------------------------------------------
kubectl config set-context --current --namespace=<your-name>
---------------------------------------------------------------------  

.   Execute the command "minikube service pages --namespace <your-name>" and it would open the application in the browser.

.   Instructions for the application to be deployed in Enterprise PKS
.. pks cli must have been installed already
.. Receive the pks-username, pks-password, pks-cluster-name and pks-api-name.
.. Execute the below command to login to the PKS

+
[source, java, numbered]
---------------------------------------------------------------------
pks login -a pks-api-name   -u pks-username  -k -p pks-password 
---------------------------------------------------------------------

. We need to create PageApplication.java and HelloController.java based on test classes

[source, java, numbered]
---------------------------------------------------------------------
pks get-credentials pks-cluster-name
---------------------------------------------------------------------

Now we are good to execute our commands in the PKS cluster

. Execute the below commands to create namespace, deployment and service in pks cluster
+
[source, java, numbered]
---------------------------------------------------------------------
kubectl -f deployment/pages-namespace.yaml
kubectl -f deployment/pages-service.yaml
kubectl -f deployment/pages-deployment.yaml
---------------------------------------------------------------------

. Verify the namespace, deployment and service are created by using the following command in the pks cluster
+ 
[source,java]
---------------------------------------------------------------------
kubectl get deployment pages --namespace <your-name>
kubectl get service pages --namespace <your-name>
---------------------------------------------------------------------

. Below command would set your default namespace to the new namespace and we don't need to suffix --namespace in all commands

+  

[source,java]
---------------------------------------------------------------------
kubectl config set-context --current --namespace=<your-name>
---------------------------------------------------------------------

. Identify the external ip of the pages service from the output of "kubectl get service pages" command.

. Commit your code to your github repository

+

[source,java]
---------------------------------------------------------------------
git add .
git commit -m "commit message"
git push -u origin master 
---------------------------------------------------------------------

== Accessing the Kubernetes Dashboard on PKS

=== Run the following command to start proxying the Kubernetes dashboard on PKS

    . kubectl proxy &
    . Wait for the output - Starting to serve on 127.0.0.1:8001
    . Open the dashboard at  http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
    . You need to provide the config file located under $home/.kube directory. Click on the three dots after 'choose kubeconfig file' .To see the file under the .kube folder , right click and select show hidden files.