= Putting your container to the Kubernetes cluster 

== Learning Outcomes
After completing the lab, you will be able to:

 . Describe how to create Kubernetes Objects
 . Describe how to write yaml files for pods, deployments and services
 . Run your Spring boot application as a docker container
 
== Get started 
Before starting the lab, pull in the kubernetes-start task.
   
   git cherry-pick kubernetes-start
   

## Step 0: Build the image


For this exercise, we're going to be using the `pages:0.1
` image built in lab-02.

Run `docker image list` and ensure `boot-pages:0.1
` is present in the list.  If not, rebuild it.

## Step 0: Ensure Kubernetes is running


1. Run `kubectl cluster-info` and `kubectl version`.  If it errored, return to exercise 0 to ensure you're

## Step 1: Craft a pod.yaml file


**Note:** Yaml files are white-space significant.  Indenting is done with **2 spaces**, not 4 spaces, not tabs.

Each Kubernetes object has an `apiVersion`, a `kind`, a `metadata` section, and a `spec` section that holds the details.

1. Create a new file in this `start` directory named `pod.yaml`

2. Write these lines:

+ 

[source, java, numbered]
---------------------------------------------------------------------
 apiVersion: v1
   kind: Pod
---------------------------------------------------------------------

   

- This says we're using a `Pod` object, and it's found in Kubernetes's `v1` namespace.

3. Write these lines:

   ```
   metadata:
     name: pages
   ```

- With this, we've named the pod `pages`.

4. Add these lines to the `metadata` section:

+
[source, java, numbered]
---------------------------------------------------------------------
  labels:
       app: pages
       version: v0.1
---------------------------------------------------------------------

- We're giving Kubernetes a bit of metadata about the pod -- a list of arbitrary name-value pairs.  We could put anything we wanted here -- service tags, environment name, your favorite color.
We'll use these when we discuss service's selectors.

   
5. The next section is the details about the pod -- the container(s) in it:

+
[source, java, numbered]
---------------------------------------------------------------------
  spec:
     containers:
---------------------------------------------------------------------

  
6. We only have a single container, let's specify the container details:

+
[source, java, numbered]
---------------------------------------------------------------------
- name: pages
---------------------------------------------------------------------

 
- The first `-` creates a new entry in the containers array.  We then name the container `pages`.

7. Let's add the image Kubernetes should pull from docker hub:

+
[source, java, numbered]
---------------------------------------------------------------------
 image: username/pages:0.1
---------------------------------------------------------------------

   
- Replace the user name with your Docker user name
Good thing we built this image previously.  Kubernetes won't need to pull it because it already exists.

8. Add the port details:

+
[source, java, numbered]
---------------------------------------------------------------------
   ports:
       - containerPort: 8080
---------------------------------------------------------------------

 
8. For reference, here's our completed container details:

+
[source, java, numbered]
---------------------------------------------------------------------
   spec:
     containers:
     - name: pages
       image: username/pages:0.1
       ports:
       - containerPort: 8080
---------------------------------------------------------------------

   

9. Save the pod.yaml file.


## Step 2: Schedule the pod


1. Open a command prompt in this directory, and run:

+
[source, java, numbered]
---------------------------------------------------------------------
    kubectl apply -f pod.yaml
---------------------------------------------------------------------


- This says "please schedule the thing I've got in the yaml file `pod.yaml`.

2. Run this command:

+
[source, java, numbered]
---------------------------------------------------------------------
     kubectl get pods
---------------------------------------------------------------------

   

- Do you see your pod?  Is it running?

3. Run this command:

+
[source, java, numbered]
---------------------------------------------------------------------
    kubectl describe pods pages
---------------------------------------------------------------------

  
- This command tells us a lot about the pod.

4. Run this command:

+
[source, java, numbered]
---------------------------------------------------------------------
   kubectl port-forward pages 8080:8080
---------------------------------------------------------------------

   
- This command won't end.  It sets up a proxy so you can browse to the pod.  This is generally not a good idea, but we're experimenting.

5. Open a browser to [http://localhost:8080/].  Do you see the site?

6. Hit `Cntrl` + `C` to break out of the port-forward command.  You can check `kubectl get pods` to see the pod is still running.

7. Run this from the terminal:

+
[source, java, numbered]
---------------------------------------------------------------------
 kubectl delete -f pod.yaml
---------------------------------------------------------------------
 
- We just scheduled Kubernetes to delete this pod.  It'll terminate the container running in it.

8. If you hurry, you can see the pod terminating:

+
[source, java, numbered]
---------------------------------------------------------------------
kubectl get pods
---------------------------------------------------------------------

  
Kubernetes Deployment
=====================

Let's scale up from one pod to many pods.

== Step 1: Craft a deployment.yaml file


1. Copy the `pod.yaml` file, and rename it `deployment.yaml`.

   **Pro tip:** Don't copy and paste the files, rather re-type them to get more experience with this content.

2. Open `deployment.yaml` in a text editor.

3. At the very top, add a bunch of blank space above `apiVersion: v1`.


4. Add these lines at the very top of the file:

+
[source, java, numbered]
---------------------------------------------------------------------
apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: pages-deployment
   spec:
---------------------------------------------------------------------

   
- This object will be a Deployment, found in the `apps/v1` namespace.  We're naming this deployment `pages-deployment`.

-  (If you're using an older version of Kubernetes, it may be in [`apps/v1beta2`](https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment) or [`apps/v1beta1`](https://v1-7.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment) namespace.)

5. In the `spec` section of the Deployment, let's add content:

+
[source, java, numbered]
---------------------------------------------------------------------
replicas: 2
---------------------------------------------------------------------

  

- This says we'd like 2 pods running.  If Kubernetes notices a pod has failed, it'll kill off that pod and spin up a new one.

6. Still in the `spec` section, add these lines:

+
[source, java, numbered]
---------------------------------------------------------------------
selector:
       matchLabels:
         app: pages
---------------------------------------------------------------------

   
- This is how Kubernetes knows which pods relate to this deployment.  It looks for pods that have metadata that includes `app: pages`.  The pods can have additional metadata tags, but to be part of this deployment, they must have at least this tag.

7. Last piece in the `spec` section:

+
[source, java, numbered]
---------------------------------------------------------------------
template:
---------------------------------------------------------------------

   

- We're about to tell Kubernetes how to build each pod.

8. Indent the original `pod.yaml` content by 4 spaces so it's nested in the template like so:

+
[source, java, numbered]
---------------------------------------------------------------------
  template:
       apiVersion: v1
       kind: Pod
       metadata:
         name: pages
         labels:
           app: pages
           version: v0.1
       spec:
         containers:
         - ...
---------------------------------------------------------------------

  

 - We've defined what the pod would look like, but there's some things that don't fit here.  The deployment file is **not valid** yet.

9. **Remove** these lines from the template:


+
[source, java, numbered]
---------------------------------------------------------------------
apiVersion: v1
       kind: Pod
---------------------------------------------------------------------

   

- Deployments can only create pods, so we remove this redundancy.

10. **Remove** this line from the template:

+
[source, java, numbered]
---------------------------------------------------------------------
name: pages
---------------------------------------------------------------------

    

- We can't have two pods with the same name, so we'll let Kubernetes auto-generate pod names.

11. Save the deployment.yaml file.


== Step 2: Schedule the deployment


1. From a command prompt in the same directory as the `deployment.yaml` file, type:

+
[source, java, numbered]
---------------------------------------------------------------------
  kubectl apply -f deployment.yaml
---------------------------------------------------------------------

   
- This says "please schedule the thing I've got in the yaml file `deployment.yaml`.

2. Run this command:


+
[source, java, numbered]
---------------------------------------------------------------------
 kubectl get deployments
---------------------------------------------------------------------

   

- Do you see your deployment?

3. Run this command:

+
[source, java, numbered]
---------------------------------------------------------------------
 kubectl get pods
---------------------------------------------------------------------

 

- Do you see the pods spinning up?


4. Run this command:

+
[source, java, numbered]
---------------------------------------------------------------------
kubectl describe deployment pages-deployment
---------------------------------------------------------------------


- This command tells us a lot about the deployment.

4. Run this command:

+
[source, java, numbered]
---------------------------------------------------------------------
kubectl get all
---------------------------------------------------------------------

  

- This shows **most** of the things running in Kubernetes in the default namespace.  Here it shows both the deployment and the pods.

5. Let's leave the deployment running, and next build a service to NAT traffic into the pods.


Kubernetes Service
==================

Now that we've got a deployment running, let's route traffic into it.

== Step 1: Craft a service.yaml file


1. Create a new file named `service.yaml`.

2. Write these lines:

+
[source, java, numbered]
---------------------------------------------------------------------
apiVersion: v1
   kind: Service
---------------------------------------------------------------------


- This says we're using a `Service` object, and it's found in Kubernetes's `v1` namespace.

3. Next, we'll define the `metadata` section:

+
[source, java, numbered]
---------------------------------------------------------------------
 metadata:
     name: pages-service
---------------------------------------------------------------------


- We'll name this service `pages-service`, matching our theme of `pages-deployment` and `pages` pods.

4. The 4th section is the `spec` section:

+
[source, java, numbered]
---------------------------------------------------------------------
  spec:
---------------------------------------------------------------------

  

5. Here's some details about the service:

+
[source, java, numbered]
---------------------------------------------------------------------
  type: NodePort
---------------------------------------------------------------------


- A `NodePort` service creates an inbound port on each node in the cluster.  Kubernetes randomly picks a port in the 30,000 range.  

6. Add these lines:

+
[source, java, numbered]
---------------------------------------------------------------------
  selector:
       app: pages
---------------------------------------------------------------------


- Here we define which pods will get traffic from this service.  The service will locate all pods within the cluster that have `metadata` that includes `app: pages`.  The pods may have other metadata, but without this metadata, they won't receive traffic.

   In effect, this metadata match is the glue that connects services and pods.

7. Add these lines, indented to match the `selector` section:

+
[source, java, numbered]
---------------------------------------------------------------------
  ports:
     - port: 8080
       targetPort: 8080
---------------------------------------------------------------------


- This tells us that the port Kubernetes assigns to this `NodePort` will get routed to the service's port (`8080`, though we'll not use it this way), which will in turn get routed to the matching pods' port `8080`.

8. With that, we're done with the service.  Save the service.yaml file.


== Step 2: Schedule the service


1. From the command prompt, type:

+
[source, java, numbered]
---------------------------------------------------------------------
  kubectl apply -f service.yaml
---------------------------------------------------------------------

  

- This says "please schedule the thing I've got in the yaml file `service.yaml`.

2. Run this command:

+
[source, java, numbered]
---------------------------------------------------------------------
  kubectl get services
---------------------------------------------------------------------



Do you see the service?

3. Run this command:

+
[source, java, numbered]
---------------------------------------------------------------------
 kubectl describe service pages-service
---------------------------------------------------------------------


- This command tells us a lot about the service including the `NodePort` that Kubernetes randomly picked.

4. Open a browser to `http://localhost:NODE_PORT/`, replacing `NODE_PORT` with the `NodePort` you found in step 3.  

Get the logs
------------

Let's get the console logs from Kubernetes.

1. From the command prompt:

+
[source, java, numbered]
---------------------------------------------------------------------
kubectl get all
---------------------------------------------------------------------
  
- Locate the two pods

2. Run this command

+
[source, java, numbered]
---------------------------------------------------------------------
kubectl logs pod/pages-deployment-...
---------------------------------------------------------------------
  


- substituting `...` for the first pod name above.

3. Run the same command for the other pod.

